# Generated by Django 5.2 on 2025-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
